name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - libiconv=1.16
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzlib=1.2.11
  - lxml=4.7.1
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.9.7
  - python-docx=0.8.11
  - python_abi=3.9
  - setuptools=58.0.4
  - sqlite=3.37.0
  - tzdata=2021e
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - bpemb==0.3.3
    - cffi==1.15.0
    - chardet==4.0.0
    - charset-normalizer==2.0.11
    - click==8.0.3
    - colorama==0.4.4
    - conllu==4.4.1
    - cryptography==36.0.1
    - cycler==0.11.0
    - cython==0.29.23
    - deprecated==1.2.13
    - doc2text==0.2.4
    - filelock==3.4.2
    - flair==0.10
    - fonttools==4.29.1
    - ftfy==6.0.3
    - future==0.18.2
    - gdown==3.12.2
    - gensim==4.1.2
    - huggingface-hub==0.4.0
    - idna==3.3
    - importlib-metadata==3.10.1
    - janome==0.4.1
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - konoha==4.6.5
    - langdetect==1.0.9
    - matplotlib==3.5.1
    - mime==0.1.0
    - more-itertools==8.8.0
    - mpld3==0.3
    - numpy==1.22.1
    - overrides==3.1.0
    - packaging==21.3
    - pdfminer-six==20211012
    - pdfplumber==0.6.0
    - pillow==9.0.1
    - protobuf==3.19.4
    - pycparser==2.21
    - pyparsing==3.0.7
    - pypdf2==1.26.0
    - pysocks==1.7.1
    - pytesseract==0.3.8
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - regex==2022.1.18
    - requests==2.27.1
    - sacremoses==0.0.47
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - segtok==1.5.11
    - sentencepiece==0.1.95
    - six==1.16.0
    - smart-open==5.2.1
    - sqlitedict==1.7.0
    - tabulate==0.8.9
    - threadpoolctl==3.1.0
    - tokenizers==0.10.3
    - torch==1.10.2
    - tqdm==4.62.3
    - transformers==4.15.0
    - typing-extensions==4.0.1
    - urllib3==1.26.8
    - wand==0.6.7
    - wcwidth==0.2.5
    - wikipedia-api==0.5.4
    - wrapt==1.13.3
    - zipp==3.7.0
